### ISSUE TITLE
macOS Playback Issue (V2.1.0+)

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#152]
I tried everything and I haven’t figure out what to do to fix this issue, I can’t find many people to reproduce this issue and only one more person like me too.

After the V2.1.0, when you play the video, they get shatter and in the playback and it happened depend on your chunk size.

**Comment by haljordan2814** [comment]
2.1.0 had various playback issues. It is recommended at present to use 2.0 , or 2.1.1 . Rebuild your cache db on either of the aforementioned versions and you should see improvement in playback. Test both to see if you get improvement with either.

**Comment by zenjabba** [comment]
I've tried the same with with Plexdrive with MongoDB and it seems to playback fine. Can you compile a macosx build?

**Comment by dany20mh** [comment]
I did that from you the MongoDB branch too and I install the Mongo on macOS and start it and it did the cache, but the playback issue is still there.

The fact the the issue is change with the way you modify the chunk size, for example if I put the chunk size on 30Mb, it will get shatter and glitches around 15-20 second of the video and if I put lower like default 5Mb, it will do that on 2-5 second of the videos.

I tried 2.1.1 and that has the problem too, and I did the installation on another macOS too and the problem is too.

Also another person in Stack Channel did the same thing too, he wasn’t using Plex, he was using VLC, and he get the same problem with newer version.

So I don’t know what else I can do to fix this problem.

[plexdrive-mongodb.zip](https://github.com/dweidenfeld/plexdrive/files/1051014/plexdrive-mongodb.zip)

This file is the latest version from MongoDB branch and I still have problem with it.

**Comment by dany20mh** [comment]
This is a log that I have with -v4 before the playback and when it stoped and a few second after it.

https://pastebin.com/LhBqJ8X5

**Comment by dweidenfeld** [comment]
Will be added/fixed with 
#67

**Comment by dany20mh** [comment]
@dweidenfeld @zenjabba 

As for zenjabba suggestion, I tried the new branch also (playback-manager), it's acting a little bit better, but the problem is still there.

**Comment by Fudge** [comment]
I think I've figured out what happens on OSX, and have been able to fix it on both the latest develop version and master. 

In chunk/storage.go, loadFromDisk function, change
    eOffset := int64(math.Min(float64(size), float64(len(buf))))
to 
    eOffset := int64(math.Min(float64(size), float64(n)))

Without this change, I get a corrupted stream on each chunk change or if the player requested to read more than chunkSize, with this change it plays perfectly.

**Comment by zenjabba** [comment]
mind

**Comment by dweidenfeld** [comment]
This has to be tested very good, because this logic was already implemented and had huge side effects on the stability so that plexdrive crashed several times.
As I can see @zenjabba already merged everything by himself, so you'll have to test if this works for you.

**Comment by zenjabba** [comment]
I’m already testing it on my mac and I have the original problem reporter testing it tonight

**Comment by dweidenfeld** [comment]
Yep.. The crashes only occurr on linux

**Comment by zenjabba** [comment]
Updated my linux testing environment with the new version. 16 stream testing underway.

**Comment by Fudge** [comment]
At least on my version of go (1.8.3) and OSX (10.12.5) with mplayer, len(buf) regularly returns a number larger than n  around chunk end. 

    16M chunk size:
    [PLEXDRIVE-5.0] [2017-07-07 21:02] DEBUG  : size[8388608], n[8384513], len[8388608]
    [PLEXDRIVE-5.0] [2017-07-07 21:02] DEBUG  : size[4095], n[4095], len[4095]
    [PLEXDRIVE-5.0] [2017-07-07 21:02] DEBUG  : size[16777216], n[16773121], len[16777216]
    [PLEXDRIVE-5.0] [2017-07-07 21:02] DEBUG  : size[4095], n[4095], len[4095]

    8M chunk size:
    [PLEXDRIVE-5.0] [2017-07-07 21:13] DEBUG  : size[16777216], n[4997121], len[16777216]
    [PLEXDRIVE-5.0] [2017-07-07 21:13] DEBUG  : size[11780095], n[8388608], len[11780095]

Since len(buf) returns the size of the slice, and not actual bytes read, don't you have to use n? 
What happens if you read 8M of a chunk, then request 16M more with a 16M chunk size? In my enviroment len(buf) would be 16M while n would be 8M.

**Comment by dany20mh** [comment]
@dweidenfeld I can confirm the problem of Playback Issue is **fixed**, at least I tried two files that I know there was problem playing them with new version and they work perfectly and buffer was very good too.
