### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#9]
Hi,

So I have some files are missing in the drive, when I can see them inside the WebUI, but it’s not there in the mount.

If you need any debug or anything let me know.

That’s how I mount the drive:
./plexdrive -log-level 2 -temp /Volumes/Backup/plexdrive -fuse-options allow_other -chunk-size 8242880 ./mtng2

<img width="411" alt="screen shot 2017-05-04 at 2 51 13 pm" src="https://cloud.githubusercontent.com/assets/5872728/25719997/53801c7c-30d9-11e7-92bd-54a733fb9975.png">
<img width="484" alt="screen shot 2017-05-04 at 2 50 30 pm" src="https://cloud.githubusercontent.com/assets/5872728/25719998/5384d1d6-30d9-11e7-9874-6de1974b290f.png">

**Comment by dweidenfeld** [comment]
I think this issue occurs because the cache database has been corrupted (or not even been built correctly).
Yesterday I have implemented a fix for exactly this problem. The fix will be included in the next version.

**Comment by dany20mh** [comment]
I still have the problem and the file is still missing, so what should I do now ?
